config/routes.rb
Rails.application.routes.draw do
  resources :tweets do
    member do
      get "search"
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
    root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    include PgSearch::Model
    pg_search_scope :search_full_text,
                    against: {
                        username: 'A'

                    }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    Pagy::DEFAULT[:items] = 10
    include Pagy::Backend

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  def user_image_url
    Faker::Avatar.image
  end
  # GET /tweets or /tweets.json
  def index
    @pagy, @tweets = pagy(Tweet.all)
    if params[:query_text].present?
      @pagy, @tweets = pagy(@tweets.search_full_text(params[:query_text]))
      
    end 
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:description, :username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
    include Pagy::Frontend
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio Clon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </head>

  <body>

  <script src="https://kit.fontawesome.com/fcc48490dd.js" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, class: "text-center bg-primary border p-4 col-md-12") do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<h1 class="text-center bg-info text-light"> Tweets <i class="fa-brands fa-twitter fa-lg" style="color: #ffffff;"></i> </h1>
<div id="tweets" class="d-flex flex-column align-items-center">
  <% @tweets.each do |tweet| %>
    <div class="card mx-2 my-2 w-50">
      <div class="card-body d-flex">
        <div class="user-image mr-3">
          <%= image_tag tweet.image, class: "rounded-circle", width: 40, height: 40 %>
        </div>
        <div>
          <h5 class="card-title text-primary mb-1"> <%= tweet.id%> User: <i class="fa-solid fa-star fa-sm" style="color: #85fffd;"></i> @<%= tweet.username %></h5>
          <p class="card-text"><%= tweet.description %></p>
            <div class="d-inline-block">
              <%= link_to "Editar", edit_tweet_path(tweet), class: "btn btn-primary mr-2" %>
            </div>
            <div class="d-inline-block">
              <%= button_to "Eliminar", tweet_path(tweet), class: "btn btn-danger", method: :delete %>
            </div>
          <%= tweet.updated_at%>
        </div>
      </div>
    </div>
  <% end %>
</div>
<%= link_to "New tweet", new_tweet_path %>

app/views/tweets/edit.html.erb
<h1 class="text-center bg-info text-light"> Tweets <i class="fa-brands fa-twitter fa-lg" style="color: #ffffff;"></i> </h1>
<div class="container d-flex align-items-center justify-content-center" style="height: 80vh;">
        <div class="text-center">
          <h1>Editing tweet</h1>

          <%= render "form", tweet: @tweet %>

          <br>

          <div>
            <%= link_to "Show this tweet", @tweet %> |
            <%= link_to "Back to tweets", tweets_path %>
          </div>
    </div>
</div>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center bg-info text-light"> Tweets <i class="fa-brands fa-twitter fa-lg" style="color: #ffffff;"></i> </h1>
<%= form_with url: tweets_path, method: :get, id: "search-form", class: "form-inline justify-content-end" do |form| %>
  <%= form.text_field :query_text, placeholder: t('Username text'), value: params[:query_text], id: "query-text", class: "form-control form-control-sm mr-2" %>
  <%= form.submit "Buscar", class: "btn btn-primary btn-sm" %>
<% end %>
<div id="tweets" class="d-flex flex-column align-items-center">
  <% @tweets.each do |tweet| %>
    <div class="card mx-2 my-2 w-50">
      <div class="card-body d-flex">
        <div class="user-image mr-3">
          <%= image_tag tweet.image, class: "rounded-circle", width: 40, height: 40 %>
        </div>
        <div>
          <h5 class="card-title text-primary mb-1"> <%= tweet.id%> User: <i class="fa-solid fa-star fa-sm" style="color: #85fffd;"></i> @<%= tweet.username %></h5>
          <p class="card-text"><%= tweet.description %></p>
            <div class="d-inline-block">
              <%= link_to "Editar", edit_tweet_path(tweet), class: "btn btn-primary mr-2" %>
            </div>
            <div class="d-inline-block">
              <%= button_to "Eliminar", tweet_path(tweet), class: "btn btn-danger", method: :delete %>
            </div>
          <%= tweet.updated_at%>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "New tweet", new_tweet_path %>
<%=raw pagy_nav(@pagy)%>
<%= link_to "Back to tweets", tweets_path %>

app/views/tweets/new.html.erb
<h1 class="text-center bg-info text-light"> Tweets <i class="fa-brands fa-twitter fa-lg" style="color: #ffffff;"></i> </h1>

<div class="container d-flex align-items-center justify-content-center" style="height: 80vh;">
  <div class="text-center">
    <h1>Form New tweet</h1>
    <%= render "form", tweet: @tweet %>

    <br>

    <div>
      <%= link_to "Back to tweets", tweets_path %>
    </div>
  </div>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Back to tweets", tweets_path %>

  <%= button_to "Destroy this tweet", @tweet, method: :delete %>
</div>